// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from '@tauri-apps/api/core';
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	killSidecar: () => __TAURI_INVOKE<void>("kill_sidecar"),
	logFrontendError: (level: string, message: string) => __TAURI_INVOKE<void>("log_frontend_error", { level, message }),
	logInfo: () => __TAURI_INVOKE<LogInfo>("log_info"),
	cleanLogs: (retentionDays: number) => __TAURI_INVOKE<number>("clean_logs", { retentionDays }),
	toggleDevtools: () => __TAURI_INVOKE<void>("toggle_devtools"),
	restartSidecar: () => __TAURI_INVOKE<null>("restart_sidecar"),
	startProjectSidecar: (directory: string) => __TAURI_INVOKE<ProjectSidecarInfo>("start_project_sidecar", { directory }),
	stopProjectSidecar: (directory: string) => __TAURI_INVOKE<null>("stop_project_sidecar", { directory }),
	getAllProjectSidecars: () => __TAURI_INVOKE<ProjectSidecarInfo[]>("get_all_project_sidecars"),
	getSidecarAuthHeader: (directory: string) => __TAURI_INVOKE<string | null>("get_sidecar_auth_header", { directory }),
	monitorProjectSidecar: (directory: string) => __TAURI_INVOKE<null>("monitor_project_sidecar", { directory }),
	installCli: () => __TAURI_INVOKE<string>("install_cli"),
	awaitInitialization: (events: Channel) => __TAURI_INVOKE<ServerReadyData>("await_initialization", { events }),
	getDefaultServerUrl: () => __TAURI_INVOKE<string | null>("get_default_server_url"),
	setDefaultServerUrl: (url: string | null) => __TAURI_INVOKE<null>("set_default_server_url", { url }),
	getGearDataDir: () => __TAURI_INVOKE<string | null>("get_gear_data_dir"),
	setGearDataDir: (dir: string | null) => __TAURI_INVOKE<null>("set_gear_data_dir", { dir }),
	getWslConfig: () => __TAURI_INVOKE<WslConfig>("get_wsl_config"),
	setWslConfig: (config: WslConfig) => __TAURI_INVOKE<null>("set_wsl_config", { config }),
	getDisplayBackend: () => __TAURI_INVOKE<"wayland" | "auto" | null>("get_display_backend"),
	setDisplayBackend: (backend: LinuxDisplayBackend) => __TAURI_INVOKE<null>("set_display_backend", { backend }),
	parseMarkdownCommand: (markdown: string) => __TAURI_INVOKE<string>("parse_markdown_command", { markdown }),
	wslPath: (path: string, mode: "windows" | "linux" | null) => __TAURI_INVOKE<string>("wsl_path", { path, mode }),
	resolveAppPath: (appName: string) => __TAURI_INVOKE<string | null>("resolve_app_path", { appName }),
	openPath: (path: string, appName: string | null) => __TAURI_INVOKE<null>("open_path", { path, appName }),
	getSmartLayerConfig: () => __TAURI_INVOKE<{
	url: string,
	username: string,
	has_password: boolean,
} | null>("get_smart_layer_config"),
	getSmartLayerAuthHeader: () => __TAURI_INVOKE<string | null>("get_smart_layer_auth_header"),
	listSystemFonts: () => __TAURI_INVOKE<string[]>("list_system_fonts"),
};

/** Events */
export const events = {
	sidecarRestartFailed: makeEvent<SidecarRestartFailed>("sidecar-restart-failed"),
	smartLayerReadyData: makeEvent<SmartLayerReadyData>("smart-layer-ready-data"),
	sqliteMigrationProgress: makeEvent<SqliteMigrationProgress>("sqlite-migration-progress"),
};

/* Types */
export type InitStep = { phase: "server_waiting" } | { phase: "sqlite_waiting" } | { phase: "done" };

export type LinuxDisplayBackend = "wayland" | "auto";

export type LogInfo = {
		root: string,
		today_dir: string,
		today: string,
	};

export type ProjectSidecarInfo = {
		directory: string,
		url: string,
		port: number,
		has_password: boolean,
	};

export type ServerReadyData = {
		url: string,
		username: string | null,
		password: string | null,
	};

export type SidecarRestartFailed = {
		attempt: number,
		max_attempts: number,
		reason: string,
	};

/**
 * Smart Layer connection data exposed to the WebView.
 * Password is never sent to the frontend — only `has_password` indicates
 * whether credentials are available. Use `get_smart_layer_auth_header`
 * to obtain a pre-computed Authorization header instead.
 */
export type SmartLayerReadyData = {
		url: string,
		username: string,
		has_password: boolean,
	};

export type SqliteMigrationProgress = "InProgress" | "Done";

export type WslConfig = {
		enabled: boolean,
	};

export type WslPathMode = "windows" | "linux";

/* Tauri Specta runtime */
function makeEvent<T>(name: string) {
    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
        emit: (payload: T) => __TAURI_EVENT.emit(name, payload) as unknown as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
        emit: (payload: T) => target.emit(name, payload) as unknown as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    });

    return Object.assign(fn, base);
}

