//! Bincode storage — fast binary serialization of the in-memory graph.
//!
//! Replaces SQLite as the primary persistence layer for KG data.
//! - Indexing: build in-memory petgraph → save to bincode file (~1s for 10k files)
//! - Loading: read bincode file → deserialize to petgraph (<1s for 10k files)
//! - Atomic writes: write to .tmp file → rename
//! - Version checking: schema version mismatch triggers re-index

use std::collections::HashMap;
use std::io::{BufReader, BufWriter, Write};
use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex};
use std::thread;

use anyhow::{Context, Result};
use bincode::Options;
use serde::{Deserialize, Serialize};

use duo_types::{KGEdge, KGNode};

/// Current snapshot format version. Increment when GraphSnapshot schema changes.
pub(crate) const CURRENT_SNAPSHOT_VERSION: u32 = 4;

/// Maximum cache file size (500 MB). Prevents OOM when deserializing corrupt files.
const MAX_CACHE_FILE_SIZE: u64 = 500 * 1024 * 1024;

/// In-memory graph + metadata, serialized as a single bincode file.
///
/// Note: KGNode/KGEdge contain `Option<HashMap<String, serde_json::Value>>`
/// properties. `serde_json::Value` does not serialize correctly with bincode
/// (enum tag mismatch). We convert properties to JSON strings before serializing.
#[derive(Serialize, Deserialize, Clone)]
pub struct GraphSnapshot {
    /// Snapshot format version. Mismatch triggers re-index.
    pub version: u32,
    /// Project ID this graph belongs to.
    pub project_id: String,
    /// All nodes (flat vec, not petgraph — avoids serde_json::Value bincode issues).
    pub nodes: Vec<BincodeNode>,
    /// All edges (flat vec).
    pub edges: Vec<BincodeEdge>,
    /// Per-file mtime + content hash, used for incremental update detection.
    pub file_hashes: HashMap<String, FileHash>,
    /// Index level: "variable" (full) or "function" (basic).
    pub index_level: String,
}

/// Bincode-compatible node (properties stored as JSON string).
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct BincodeNode {
    pub id: String,
    pub label: String,
    pub node_type: String,
    pub properties_json: Option<String>,
    pub project_id: String,
}

/// Bincode-compatible edge (properties stored as JSON string).
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct BincodeEdge {
    pub id: String,
    pub source_id: String,
    pub target_id: String,
    pub relation: String,
    pub weight: Option<f64>,
    pub properties_json: Option<String>,
    pub project_id: String,
}

impl From<&KGNode> for BincodeNode {
    fn from(n: &KGNode) -> Self {
        BincodeNode {
            id: n.id.clone(),
            label: n.label.clone(),
            node_type: n.node_type.clone(),
            properties_json: n
                .properties
                .as_ref()
                .map(|p| serde_json::to_string(p).unwrap_or_else(|_| "{}".to_string())),
            project_id: n.project_id.clone(),
        }
    }
}

impl From<BincodeNode> for KGNode {
    fn from(n: BincodeNode) -> Self {
        KGNode {
            id: n.id,
            label: n.label,
            node_type: n.node_type,
            properties: n
                .properties_json
                .and_then(|s| serde_json::from_str(&s).ok()),
            project_id: n.project_id,
        }
    }
}

impl From<&KGEdge> for BincodeEdge {
    fn from(e: &KGEdge) -> Self {
        BincodeEdge {
            id: e.id.clone(),
            source_id: e.source_id.clone(),
            target_id: e.target_id.clone(),
            relation: e.relation.clone(),
            weight: e.weight,
            properties_json: e
                .properties
                .as_ref()
                .map(|p| serde_json::to_string(p).unwrap_or_else(|_| "{}".to_string())),
            project_id: e.project_id.clone(),
        }
    }
}

impl From<BincodeEdge> for KGEdge {
    fn from(e: BincodeEdge) -> Self {
        KGEdge {
            id: e.id,
            source_id: e.source_id,
            target_id: e.target_id,
            relation: e.relation,
            weight: e.weight,
            properties: e
                .properties_json
                .and_then(|s| serde_json::from_str(&s).ok()),
            project_id: e.project_id,
        }
    }
}

/// Per-file metadata for incremental update detection.
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct FileHash {
    /// File modification time (Unix seconds).
    pub mtime: u64,
    /// File size in bytes. Used together with `mtime` as a cheap pre-filter
    /// before the (expensive) content hash: if both match the cached values the
    /// file is trusted unchanged and its content is not re-read.
    #[serde(default)]
    pub size: u64,
    /// SipHash content hash generated by Rust's DefaultHasher.
    pub content_hash: String,
}

/// Binary file storage for graph snapshots.
///
/// Each project gets one file: `{cache_dir}/{sanitized_project_id}.bin`
pub struct BincodeStorage {
    cache_dir: PathBuf,
}

impl BincodeStorage {
    /// Create a new BincodeStorage. Creates the cache directory if needed.
    pub fn new(data_dir: &Path) -> Result<Self> {
        let cache_dir = data_dir.join("kg_cache");
        std::fs::create_dir_all(&cache_dir)
            .with_context(|| format!("Failed to create kg_cache dir: {:?}", cache_dir))?;
        Ok(Self { cache_dir })
    }

    /// Save a graph snapshot to bincode file (atomic write via tmp + rename).
    pub fn save(&self, snapshot: &GraphSnapshot) -> Result<()> {
        let path = self.cache_path(&snapshot.project_id);
        let tmp_path = path.with_extension("bin.tmp");

        // Clean up stale tmp file from previous crashed write
        if tmp_path.exists() {
            let _ = std::fs::remove_file(&tmp_path);
        }

        // Serialize to tmp file
        let file = std::fs::File::create(&tmp_path)
            .with_context(|| format!("Failed to create tmp file: {:?}", tmp_path))?;
        let mut writer = BufWriter::new(file);
        bincode::options()
            .with_limit(MAX_CACHE_FILE_SIZE)
            .serialize_into(&mut writer, snapshot)
            .with_context(|| "Failed to serialize graph snapshot")?;
        writer.flush().with_context(|| "Failed to flush writer")?;
        drop(writer);

        // Atomic replace
        std::fs::rename(&tmp_path, &path)
            .with_context(|| format!("Failed to rename tmp file to {:?}", path))?;

        tracing::debug!(
            project_id = %snapshot.project_id,
            path = ?path,
            "Graph snapshot saved"
        );

        Ok(())
    }

    /// Load a graph snapshot from bincode file.
    /// Returns Ok(None) if file doesn't exist, is corrupted, or version mismatch.
    pub fn load(&self, project_id: &str) -> Result<Option<GraphSnapshot>> {
        let path = self.cache_path(project_id);
        if !path.exists() {
            return Ok(None);
        }

        // Check file size before deserializing (bincode can attempt huge allocs on corrupt data)
        let file_size = std::fs::metadata(&path).map(|m| m.len()).unwrap_or(0);
        if file_size > MAX_CACHE_FILE_SIZE {
            tracing::warn!(project_id, file_size, "Cache file too large, deleting");
            let _ = std::fs::remove_file(&path);
            return Ok(None);
        }

        let file = std::fs::File::open(&path)
            .with_context(|| format!("Failed to open cache file: {:?}", path))?;
        let reader = BufReader::new(file);

        // Use bincode with size limit to prevent OOM on corrupt data
        let result = bincode::options()
            .with_limit(MAX_CACHE_FILE_SIZE)
            .allow_trailing_bytes()
            .deserialize_from::<_, GraphSnapshot>(reader);

        match result {
            Ok(snapshot) => {
                if snapshot.version != CURRENT_SNAPSHOT_VERSION {
                    tracing::warn!(
                        project_id,
                        cached_version = snapshot.version,
                        current_version = CURRENT_SNAPSHOT_VERSION,
                        "Cache version mismatch, will re-index"
                    );
                    let _ = std::fs::remove_file(&path);
                    return Ok(None);
                }
                tracing::debug!(
                    project_id,
                    nodes = snapshot.nodes.len(),
                    edges = snapshot.edges.len(),
                    "Graph snapshot loaded from cache"
                );
                Ok(Some(snapshot))
            }
            Err(e) => {
                tracing::warn!(
                    project_id,
                    error = %e,
                    "Failed to deserialize cache, deleting and re-indexing"
                );
                let _ = std::fs::remove_file(&path);
                Ok(None)
            }
        }
    }

    /// Delete the cache file for a project.
    ///
    /// Returns `Ok(true)` when a file was actually removed and `Ok(false)` when
    /// there was nothing to remove. A missing file is not an error (deletion is
    /// idempotent), but callers must be able to tell the two apart: silently
    /// reporting success for a snapshot that was never found hides project-id
    /// mismatches, which is exactly how "cleared" indexes appear to come back.
    pub fn delete(&self, project_id: &str) -> Result<bool> {
        let path = self.cache_path(project_id);
        match std::fs::remove_file(&path) {
            Ok(()) => {
                tracing::info!(project_id, path = ?path, "Cache file deleted");
                Ok(true)
            }
            // Racing with another deleter, or the snapshot never existed.
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
                tracing::warn!(
                    project_id,
                    path = ?path,
                    "No cache file found to delete (project_id may not match any snapshot)"
                );
                Ok(false)
            }
            Err(e) => Err(e).with_context(|| format!("Failed to delete cache file: {:?}", path)),
        }
    }

    /// Check if a cache file exists for the project.
    pub fn exists(&self, project_id: &str) -> bool {
        self.cache_path(project_id).exists()
    }

    /// Directory where bincode snapshots (and the index registry) are stored.
    pub fn cache_dir(&self) -> &Path {
        &self.cache_dir
    }

    /// Public accessor for a project's snapshot path (used to compute size for the
    /// settings UI). Mirrors `cache_path`.
    pub fn snapshot_path(&self, project_id: &str) -> PathBuf {
        self.cache_path(project_id)
    }

    /// Get the cache file path for a project ID.
    ///
    /// The name is derived by [`crate::project::file_stem`]: bounded, so a deep
    /// project path cannot exceed the OS path limit, and hash-suffixed, so two
    /// projects can never map onto one file.
    fn cache_path(&self, project_id: &str) -> PathBuf {
        self.cache_dir
            .join(format!("{}.bin", crate::project::file_stem(project_id)))
    }
}

/// Check if all files in the snapshot are still up-to-date.
/// Returns a list of files that have changed (modified, resized, or deleted).
///
/// Cheap pre-filter first: a file is trusted unchanged only when BOTH its
/// `mtime` and `size` match the cached values. This avoids re-reading and
/// re-hashing every file on open, which was the dominant cost when the cache
/// was fresh. The expensive content hash is no longer needed for the
/// unchanged-majority case.
///
/// Scans files concurrently across the available cores (same pattern as
/// `collect_file_hashes`) to keep open latency low for large projects.
pub fn detect_changed_files(snapshot: &GraphSnapshot, root: &Path) -> Vec<String> {
    use std::sync::atomic::{AtomicUsize, Ordering};

    let entries: Vec<(&String, &FileHash)> = snapshot.file_hashes.iter().collect();
    let entries = Arc::new(entries);
    let changed = Arc::new(Mutex::new(Vec::new()));
    let root = root.to_path_buf();

    let threads = std::thread::available_parallelism()
        .map(|n| n.get())
        .unwrap_or(4)
        .max(1);

    thread::scope(|s| {
        // Simple static chunking; files are roughly equal cost for metadata-only.
        let chunk_size = entries.len().div_ceil(threads);
        let idx = Arc::new(AtomicUsize::new(0));

        for _ in 0..threads {
            let changed = Arc::clone(&changed);
            let entries = Arc::clone(&entries);
            let idx = Arc::clone(&idx);
            let root = root.clone();
            s.spawn(move || {
                loop {
                    let start = idx.fetch_add(chunk_size, Ordering::Relaxed);
                    if start >= entries.len() {
                        break;
                    }
                    let end = (start + chunk_size).min(entries.len());
                    for (file_path, cached) in &entries[start..end] {
                        let full_path = root.join(file_path);
                        match std::fs::metadata(&full_path) {
                            Ok(meta) => {
                                let mtime = meta
                                    .modified()
                                    .ok()
                                    .and_then(|t| t.duration_since(std::time::UNIX_EPOCH).ok())
                                    .map(|d| d.as_secs())
                                    .unwrap_or(0);
                                // Changed iff mtime OR size differs. Content hash
                                // is only needed if both match, in which case we
                                // trust the file is unchanged (no re-read).
                                if mtime != cached.mtime || meta.len() != cached.size {
                                    duo_utils::sync::lock(&changed).push((*file_path).clone());
                                }
                            }
                            Err(_) => {
                                // File deleted
                                duo_utils::sync::lock(&changed).push((*file_path).clone());
                            }
                        }
                    }
                }
            });
        }
    });

    // Note: detecting new files requires comparing with collect_source_files output.
    // That is done by the caller who has the full file list.
    let mut changed = Arc::try_unwrap(changed)
        .expect("invariant: rayon scope joined; all Arc clones have been dropped")
        .into_inner()
        .unwrap_or_else(|poisoned| poisoned.into_inner());
    changed.sort();
    changed
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_test_snapshot() -> GraphSnapshot {
        let node = BincodeNode {
            id: "function:foo@test.rs".to_string(),
            label: "foo".to_string(),
            node_type: "Function".to_string(),
            properties_json: None,
            project_id: "test_project".to_string(),
        };

        let mut file_hashes = HashMap::new();
        file_hashes.insert(
            "src/main.rs".to_string(),
            FileHash {
                mtime: 1000,
                size: 4096,
                content_hash: "abc123".to_string(),
            },
        );

        GraphSnapshot {
            version: CURRENT_SNAPSHOT_VERSION,
            project_id: "test_project".to_string(),
            nodes: vec![node],
            edges: vec![],
            file_hashes,
            index_level: "variable".to_string(),
        }
    }

    #[test]
    fn bincode_save_and_load_roundtrip() {
        let tmp_dir = std::env::temp_dir().join("kg_test_bincode_roundtrip");
        let _ = std::fs::remove_dir_all(&tmp_dir);
        let storage = BincodeStorage::new(&tmp_dir).unwrap();

        let snapshot = make_test_snapshot();
        storage.save(&snapshot).unwrap();

        let loaded = storage.load("test_project").unwrap();
        assert!(loaded.is_some());
        let loaded = loaded.unwrap();
        assert_eq!(loaded.version, CURRENT_SNAPSHOT_VERSION);
        assert_eq!(loaded.project_id, "test_project");
        assert_eq!(loaded.nodes.len(), 1);
        assert_eq!(loaded.edges.len(), 0);
        assert_eq!(loaded.index_level, "variable");
        assert_eq!(loaded.file_hashes.len(), 1);

        // Clean up
        let _ = std::fs::remove_dir_all(&tmp_dir);
    }

    #[test]
    fn bincode_load_nonexistent_returns_none() {
        let tmp_dir = std::env::temp_dir().join("kg_test_bincode_nonexistent");
        let _ = std::fs::remove_dir_all(&tmp_dir);
        let storage = BincodeStorage::new(&tmp_dir).unwrap();

        let result = storage.load("nonexistent_project").unwrap();
        assert!(result.is_none());

        let _ = std::fs::remove_dir_all(&tmp_dir);
    }

    #[test]
    fn bincode_delete_removes_file() {
        let tmp_dir = std::env::temp_dir().join("kg_test_bincode_delete");
        let _ = std::fs::remove_dir_all(&tmp_dir);
        let storage = BincodeStorage::new(&tmp_dir).unwrap();

        let snapshot = make_test_snapshot();
        storage.save(&snapshot).unwrap();
        assert!(storage.exists("test_project"));

        storage.delete("test_project").unwrap();
        assert!(!storage.exists("test_project"));

        let _ = std::fs::remove_dir_all(&tmp_dir);
    }

    #[test]
    fn bincode_corrupted_file_returns_none() {
        let tmp_dir = std::env::temp_dir().join("kg_test_bincode_corrupt");
        let _ = std::fs::remove_dir_all(&tmp_dir);
        let storage = BincodeStorage::new(&tmp_dir).unwrap();

        // Write garbage to cache file
        let path = storage.cache_path("test_project");
        std::fs::write(&path, b"not valid bincode data").unwrap();

        let result = storage.load("test_project").unwrap();
        assert!(result.is_none(), "Corrupted file should return None");

        // File should be deleted after failed load
        assert!(!path.exists(), "Corrupted file should be deleted");

        let _ = std::fs::remove_dir_all(&tmp_dir);
    }

    #[test]
    fn bincode_version_mismatch_returns_none() {
        let tmp_dir = std::env::temp_dir().join("kg_test_bincode_version");
        let _ = std::fs::remove_dir_all(&tmp_dir);
        let storage = BincodeStorage::new(&tmp_dir).unwrap();

        // Save a snapshot with wrong version
        let mut snapshot = make_test_snapshot();
        snapshot.version = 999;
        storage.save(&snapshot).unwrap();

        let result = storage.load("test_project").unwrap();
        assert!(result.is_none(), "Version mismatch should return None");

        let _ = std::fs::remove_dir_all(&tmp_dir);
    }

    #[test]
    fn bincode_cache_path_sanitizes_special_chars() {
        let tmp_dir = std::env::temp_dir().join("kg_test_bincode_path");
        let _ = std::fs::remove_dir_all(&tmp_dir);
        let storage = BincodeStorage::new(&tmp_dir).unwrap();

        let path = storage.cache_path("C:/Users/test/my project");
        let filename = path.file_name().unwrap().to_string_lossy().to_string();
        assert!(!filename.contains('/'));
        assert!(!filename.contains('\\'));
        assert!(!filename.contains(':'));
        assert!(!filename.contains(' '));

        let _ = std::fs::remove_dir_all(&tmp_dir);
    }

    #[test]
    fn bincode_save_with_edges_roundtrip() {
        let tmp_dir = std::env::temp_dir().join("kg_test_bincode_edges");
        let _ = std::fs::remove_dir_all(&tmp_dir);
        let storage = BincodeStorage::new(&tmp_dir).unwrap();

        let node1 = BincodeNode {
            id: "function:foo@a.rs".to_string(),
            label: "foo".to_string(),
            node_type: "Function".to_string(),
            properties_json: Some(r#"{"\"file\":\"a.rs\"}"#.to_string()),
            project_id: "test".to_string(),
        };
        let node2 = BincodeNode {
            id: "function:bar@b.rs".to_string(),
            label: "bar".to_string(),
            node_type: "Function".to_string(),
            properties_json: None,
            project_id: "test".to_string(),
        };
        let edge = BincodeEdge {
            id: "calls:foo→bar".to_string(),
            source_id: "function:foo@a.rs".to_string(),
            target_id: "function:bar@b.rs".to_string(),
            relation: "Calls".to_string(),
            weight: Some(0.7),
            properties_json: Some(r#"{\"confidence\":\"EXTRACTED\"}"#.to_string()),
            project_id: "test".to_string(),
        };

        let snapshot = GraphSnapshot {
            version: CURRENT_SNAPSHOT_VERSION,
            project_id: "test".to_string(),
            nodes: vec![node1, node2],
            edges: vec![edge],
            file_hashes: HashMap::new(),
            index_level: "variable".to_string(),
        };

        storage.save(&snapshot).unwrap();
        let loaded = storage.load("test").unwrap().unwrap();

        assert_eq!(loaded.nodes.len(), 2);
        assert_eq!(loaded.edges.len(), 1);

        // Verify edge data
        let edge = &loaded.edges[0];
        assert_eq!(edge.relation, "Calls");
        assert_eq!(edge.weight, Some(0.7));

        let _ = std::fs::remove_dir_all(&tmp_dir);
    }

    #[test]
    fn detect_changed_files_no_changes() {
        let snapshot = make_test_snapshot();
        let tmp_dir = std::env::temp_dir().join("kg_test_detect_nochange");
        let _ = std::fs::remove_dir_all(&tmp_dir);
        std::fs::create_dir_all(&tmp_dir).unwrap();

        // Create file with matching mtime (can't exactly match, so just test the logic)
        // This test just verifies the function doesn't crash
        let _changed = detect_changed_files(&snapshot, &tmp_dir);
        // File doesn't exist at src/main.rs relative to tmp_dir, so it should be in changed
        // (This is expected — the file is "deleted" relative to the snapshot)

        let _ = std::fs::remove_dir_all(&tmp_dir);
    }
}
