/**
 * Vendors Noto Sans SC (思源黑体, SIL OFL 1.1) into the app.
 *
 * Why this font: every other "modern Chinese" face (HarmonyOS Sans, MiSans,
 * OPPO Sans) ships a vendor licence that forbids redistribution and forbids
 * modifying the font file — which rules out both bundling and subsetting in an
 * open-source project. Noto Sans SC is OFL 1.1: use, modify and redistribute
 * freely, as long as you do not sell the font file on its own.
 *
 * The package is already split into ~101 `unicode-range` slices per weight, so
 * the browser downloads only the slices a given screen actually renders —
 * full character coverage without a 10 MB blocking download.
 *
 * Usage:  bun run scripts/fetch-fonts.ts   (from packages/app)
 */
import { existsSync, mkdirSync, writeFileSync } from "node:fs"
import { join } from "node:path"

const WEIGHTS = [400, 500, 600]
const CDN_BASE = "https://cdn.jsdelivr.net/npm/@fontsource/noto-sans-sc@5.3.0"
const FONT_DIR = "public/assets/fonts"
const OUT_CSS = "src/styles/fonts.css"
const PUBLIC_PREFIX = "/assets/fonts"
const CONCURRENCY = 12

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms))

async function fetchWithRetry(url: string, attempts = 3): Promise<Response> {
  let lastError: unknown
  for (let i = 0; i < attempts; i++) {
    try {
      const res = await fetch(url)
      if (res.ok) return res
      lastError = new Error(`HTTP ${res.status}`)
    } catch (err) {
      lastError = err
    }
    await sleep(300 * (i + 1))
  }
  throw lastError
}

/** Keeps only the woff2 source and points it at our own public directory. */
function rewriteCss(css: string): string {
  return css.replace(
    /url\(\.\/files\/([^)]+\.woff2)\)\s*format\('woff2'\)(?:,\s*url\(\.\/files\/[^)]+\.woff\)\s*format\('woff'\))?/g,
    (_match, file: string) => `url("${PUBLIC_PREFIX}/${file}") format("woff2")`,
  )
}

/**
 * SIL OFL 1.1 requires the licence (and its copyright notice) to travel with
 * the font files. Vendored next to the slices so it is bundled and shipped
 * with every distribution.
 */
async function fetchLicense() {
  const dest = join(FONT_DIR, "OFL.txt")
  if (existsSync(dest)) return
  const res = await fetchWithRetry(`${CDN_BASE}/LICENSE`)
  writeFileSync(dest, Buffer.from(await res.arrayBuffer()))
  console.log("fetched LICENSE -> OFL.txt")
}

async function main() {
  mkdirSync(FONT_DIR, { recursive: true })

  const cssParts: string[] = []
  const files = new Set<string>()

  for (const weight of WEIGHTS) {
    const res = await fetchWithRetry(`${CDN_BASE}/${weight}.css`)
    const css = await res.text()
    cssParts.push(`/* Noto Sans SC — weight ${weight} */\n${rewriteCss(css).trim()}`)
    for (const match of css.matchAll(/url\(\.\/files\/([^)]+\.woff2)\)/g)) {
      files.add(match[1]!)
    }
    console.log(`fetched ${weight}.css (${files.size} unique slices so far)`)
  }

  const queue = [...files]
  let done = 0
  let skipped = 0
  let failed = 0

  await Promise.all(
    Array.from({ length: CONCURRENCY }, async () => {
      for (;;) {
        const name = queue.pop()
        if (!name) return
        const dest = join(FONT_DIR, name)
        if (existsSync(dest)) {
          skipped++
          continue
        }
        try {
          const res = await fetchWithRetry(`${CDN_BASE}/files/${name}`)
          writeFileSync(dest, Buffer.from(await res.arrayBuffer()))
          done++
          if ((done + skipped) % 50 === 0) console.log(`  ${done + skipped}/${files.size}`)
        } catch (err) {
          failed++
          console.error(`  failed ${name}: ${(err as Error).message}`)
        }
      }
    }),
  )

  await fetchLicense()

  mkdirSync("src/styles", { recursive: true })
  writeFileSync(
    OUT_CSS,
    `/* GENERATED by scripts/fetch-fonts.ts — do not edit by hand.
   Noto Sans SC (思源黑体) · SIL Open Font License 1.1
   ${WEIGHTS.length} weights × ${files.size} unicode-range slices. */

${cssParts.join("\n\n")}
`,
    "utf8",
  )

  console.log(`\nwrote ${OUT_CSS}`)
  console.log(`slices: ${done} downloaded, ${skipped} already present, ${failed} failed`)
  if (failed > 0) process.exit(1)
}

await main()
