/**
 * Builds `src/styles/mono-cjk.css`: a monospace-shaped alias over the already
 * bundled Noto Sans SC slices.
 *
 * Problem: JetBrains Mono has no CJK glyphs, so Chinese in code/comments falls
 * back to a proportional system face that never lines up with the Latin grid.
 * A dedicated CJK monospace (Maple Mono CN, Sarasa) would be ideal, but upstream
 * only ships a 134 MB full-release zip — no per-weight or woff2 package — so
 * bundling it is not viable here.
 *
 * Solution: reuse the Noto Sans SC slices we already ship, scaled so one CJK
 * glyph occupies exactly two monospace cells. JetBrains Mono advances 0.6em per
 * cell, while a Noto Sans SC ideograph advances a full 1.0em; size-adjust
 * stretches the CJK glyph to 1.2em = 2 × 0.6em, making columns line up.
 *
 * Usage:  bun run scripts/gen-mono-cjk.ts   (from packages/app)
 */
import { readFileSync, writeFileSync } from "node:fs"

const SRC = "src/styles/fonts.css"
const OUT = "src/styles/mono-cjk.css"

/** Bump this if CJK glyphs look too large or too small next to Latin text. */
const SIZE_ADJUST = "120%"

const CJK_RANGES: Array<[number, number]> = [
  [0x2e80, 0x2eff], // CJK Radicals Supplement
  [0x3000, 0x303f], // CJK Symbols and Punctuation
  [0x3040, 0x30ff], // Hiragana + Katakana
  [0x3400, 0x4dbf], // CJK Unified Ideographs Extension A
  [0x4e00, 0x9fff], // CJK Unified Ideographs
  [0xf900, 0xfaff], // CJK Compatibility Ideographs
  [0xfe30, 0xfe4f], // CJK Compatibility Forms
  [0xff00, 0xffef], // Halfwidth and Fullwidth Forms
]

type Range = [number, number]

function parseRanges(value: string): Range[] {
  return value
    .split(",")
    .map((part) => part.trim().replace(/^U\+/i, ""))
    .flatMap((part) => {
      const [start, end] = part.split("-")
      if (!start) return []
      const lo = parseInt(start, 16)
      const hi = end ? parseInt(end, 16) : lo
      return Number.isNaN(lo) || Number.isNaN(hi) ? [] : [[lo, hi] as Range]
    })
}

function overlapsCjk(ranges: Range[]) {
  return ranges.some(([lo, hi]) => CJK_RANGES.some(([clo, chi]) => lo <= chi && clo <= hi))
}

const css = readFileSync(SRC, "utf8")
const blocks = css.split("@font-face").slice(1)
const out: string[] = []

for (const block of blocks) {
  const range = block.match(/unicode-range:\s*([^;]+);/)
  const src = block.match(/src:\s*([^;]+);/)
  const weight = block.match(/font-weight:\s*(\d+)/)
  if (!range || !src || !weight) continue
  if (!overlapsCjk(parseRanges(range[1]!))) continue

  out.push(`@font-face {
  font-family: "DuoDuo Mono CJK";
  font-style: normal;
  font-display: swap;
  font-weight: ${weight[1]};
  src: ${src[1]};
  size-adjust: ${SIZE_ADJUST};
  unicode-range: ${range[1]!};
}`)
}

writeFileSync(
  OUT,
  `/* GENERATED by scripts/gen-mono-cjk.ts — do not edit by hand.
   Monospace-shaped CJK fallback built from the bundled Noto Sans SC slices
   (思源黑体, SIL OFL 1.1). Regenerate after re-running fetch-fonts.ts. */

${out.join("\n\n")}
`,
  "utf8",
)

console.log(`wrote ${OUT}: ${out.length} CJK @font-face rules`)
