import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

// models.dev snapshot generation removed — no longer fetching third-party model data.
// Providers are sourced from config, local discovery (ollama), and custom loaders at runtime.

// Generate empty placeholder so that any remaining imports of models-snapshot.js don't break.
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.js"),
  `// @ts-nocheck\n// Auto-generated by generate.ts - do not edit\n// models.dev snapshot is no longer used. Providers come from config and local discovery.\nexport const snapshot = {}\n`,
)
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.d.ts"),
  `// Auto-generated by generate.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n`,
)
console.log("Generated empty models-snapshot.js (models.dev removed)")
