//! AST parser module — language detection from file extensions, backed by
//! per-language `tree-sitter-*` grammar crates on the tree-sitter 0.24 runtime.
//!
//! Each language `detect_language` returns is resolved to a `tree_sitter::Language`
//! via its dedicated grammar crate. Languages without a 0.24-compatible grammar crate
//! (e.g. nim/crystal), or whose published `parser.c` is ABI 15 (swift/vue/protobuf/
//! graphql/markdown/perl/ini — generated by the 0.25/0.26 CLI, rejected by the 0.24.5
//! runtime), return `None` from `init_parser`; the caller (`knowledge-graph-store`)
//! falls back to regex extraction. The following `tree-sitter-language ^0.1` based
//! crates are verified ABI 13/14 by `all_enabled_languages_abi_compatible_with_024`:
//! `sql`, `toml`, `svelte`, `clojure`, `erlang`, `ada`, `dockerfile`. The ABI-15
//! languages need vendoring + 0.24 CLI regen before they can be enabled.

use std::cell::RefCell;
use std::collections::HashMap;

use tree_sitter::Parser;

/// Simple language detector based on file extension.
///
/// Returns the canonical language name used across the crate
/// (e.g. `"rust"`, `"typescript"`, `"python"`).
pub fn detect_language(filename: &str) -> Option<String> {
    let ext = filename.rsplit('.').next().unwrap_or("").to_lowercase();
    match ext.as_str() {
        "rs" => Some("rust".to_string()),
        "ts" | "tsx" => Some("typescript".to_string()),
        "js" | "jsx" | "mjs" | "cjs" => Some("javascript".to_string()),
        "py" | "pyi" | "pyw" => Some("python".to_string()),
        "go" => Some("go".to_string()),
        "java" => Some("java".to_string()),
        "c" | "h" => Some("c".to_string()),
        "cpp" | "cc" | "cxx" | "hpp" | "hh" | "hxx" => Some("cpp".to_string()),
        "cs" => Some("csharp".to_string()),
        "rb" => Some("ruby".to_string()),
        "php" => Some("php".to_string()),
        "swift" => Some("swift".to_string()),
        "kt" | "kts" => Some("kotlin".to_string()),
        "scala" => Some("scala".to_string()),
        "lua" => Some("lua".to_string()),
        "zig" => Some("zig".to_string()),
        "toml" => Some("toml".to_string()),
        "yaml" | "yml" => Some("yaml".to_string()),
        "json" => Some("json".to_string()),
        "md" => Some("markdown".to_string()),
        "html" | "htm" => Some("html".to_string()),
        "css" | "scss" | "less" => Some("css".to_string()),
        "sql" => Some("sql".to_string()),
        "sh" | "bash" => Some("shell".to_string()),
        "dart" => Some("dart".to_string()),
        "ex" | "exs" => Some("elixir".to_string()),
        "vue" => Some("vue".to_string()),
        "svelte" => Some("svelte".to_string()),
        "proto" => Some("protobuf".to_string()),
        "graphql" | "gql" => Some("graphql".to_string()),
        "clj" => Some("clojure".to_string()),
        "erl" | "hrl" => Some("erlang".to_string()),
        "adb" | "ads" => Some("ada".to_string()),
        "dockerfile" => Some("dockerfile".to_string()),
        "nix" => Some("nix".to_string()),
        "hs" => Some("haskell".to_string()),
        "r" | "R" => Some("r".to_string()),
        "jl" => Some("julia".to_string()),
        "ml" | "mli" => Some("ocaml".to_string()),
        "pp" | "pas" => Some("pascal".to_string()),
        "ps1" | "psm1" => Some("powershell".to_string()),
        "f90" | "f95" | "for" | "f" => Some("fortran".to_string()),
        "sol" => Some("solidity".to_string()),
        "xml" | "xsl" | "xslt" | "svg" => Some("xml".to_string()),
        "cmake" | "CMakeLists.txt" => Some("cmake".to_string()),
        "fish" => Some("fish".to_string()),
        _ => None,
    }
}

/// Resolve the `tree_sitter::Language` for a canonical language name.
///
/// Returns `None` when there is no 0.24-compatible grammar crate for the language.
/// Most crates expose a `LANGUAGE: LanguageFn` constant; a few (`tree-sitter-lua`,
/// `tree-sitter-dart`, `tree-sitter-elixir`, `tree-sitter-haskell`,
/// `tree-sitter-powershell`, `tree-sitter-cmake`, `tree-sitter-fish`) instead
/// expose a `language() -> Language` function; `tree-sitter-xml` exposes
/// `LANGUAGE_XML` / `LANGUAGE_DTD`.
fn language_for(language: &str) -> Option<tree_sitter::Language> {
    let lang: tree_sitter::Language = match language {
        "rust" => tree_sitter_rust::LANGUAGE.into(),
        "typescript" => tree_sitter_typescript::LANGUAGE_TYPESCRIPT.into(),
        "javascript" | "js" => tree_sitter_javascript::LANGUAGE.into(),
        "python" | "py" => tree_sitter_python::LANGUAGE.into(),
        "go" => tree_sitter_go::LANGUAGE.into(),
        "java" => tree_sitter_java::LANGUAGE.into(),
        "c" => tree_sitter_c::LANGUAGE.into(),
        "cpp" | "c++" => tree_sitter_cpp::LANGUAGE.into(),
        "csharp" | "c#" => tree_sitter_c_sharp::LANGUAGE.into(),
        "ruby" => tree_sitter_ruby::LANGUAGE.into(),
        "scala" => tree_sitter_scala::LANGUAGE.into(),
        "php" => tree_sitter_php::LANGUAGE_PHP.into(),
        // These crates expose `language() -> Language` (no `LANGUAGE` const).
        "lua" => tree_sitter_lua::language(),
        "dart" => tree_sitter_dart::language(),
        "elixir" => tree_sitter_elixir::language(),
        "haskell" | "hs" => tree_sitter_haskell::language(),
        "powershell" => tree_sitter_powershell::language(),
        "cmake" => tree_sitter_cmake::language(),
        "fish" => tree_sitter_fish::language(),
        "xml" => tree_sitter_xml::LANGUAGE_XML.into(),
        "yaml" => tree_sitter_yaml::LANGUAGE.into(),
        "json" => tree_sitter_json::LANGUAGE.into(),
        "html" => tree_sitter_html::LANGUAGE.into(),
        "css" => tree_sitter_css::LANGUAGE.into(),
        "shell" | "bash" | "sh" => tree_sitter_bash::LANGUAGE.into(),
        "nix" => tree_sitter_nix::LANGUAGE.into(),
        "ocaml" | "ml" | "mli" => tree_sitter_ocaml::LANGUAGE_OCAML.into(),
        "pascal" => tree_sitter_pascal::LANGUAGE.into(),
        "r" => tree_sitter_r::LANGUAGE.into(),
        "fortran" => tree_sitter_fortran::LANGUAGE.into(),
        "solidity" => tree_sitter_solidity::LANGUAGE.into(),
        "julia" => tree_sitter_julia::LANGUAGE.into(),
        "kotlin" | "kt" | "kts" => tree_sitter_kotlin_ng::LANGUAGE.into(),
        "zig" => tree_sitter_zig::LANGUAGE.into(),
        // SQL: tree-sitter-sequel (derekstride). Uses the official
        // `tree-sitter-language ^0.1` abstraction, so it shares our single
        // tree-sitter 0.24.5 runtime. ABI must be 13/14 (see
        // `sql_parser_abi_compatible_with_024`).
        "sql" => tree_sitter_sequel::LANGUAGE.into(),
        // ── 额外语言（tree-sitter-language ^0.1 抽象层，ABI 13/14，0.24.5 兼容）──
        // 兼容性以 `all_enabled_languages_abi_compatible_with_024` 测试为证。
        // 注意：swift/vue/protobuf/graphql/markdown/perl/ini 发布的 parser.c 为 ABI 15，
        // 被 0.24.5 拒绝，需 vendoring + 0.24 CLI regen 后才能加入（见 workspace Cargo.toml）。
        "toml" => tree_sitter_toml_ng::LANGUAGE.into(),
        "svelte" => tree_sitter_svelte_next::LANGUAGE.into(),
        "clojure" => tree_sitter_clojure_orchard::LANGUAGE.into(),
        "erlang" => tree_sitter_erlang::LANGUAGE.into(),
        "ada" => tree_sitter_ada::LANGUAGE.into(),
        // dockerfile-updated (camdencheek) is a classic `tree-sitter` crate
        // (normal `tree-sitter` dep, not tree-sitter-language), so it exposes a
        // `language() -> Language` fn rather than a `LANGUAGE` const.
        "dockerfile" => tree_sitter_dockerfile_updated::language(),
        _ => return None,
    };
    Some(lang)
}

/// Initialize a `Parser` for the given language.
///
/// Returns `None` if the language is not supported by a 0.24-compatible grammar
/// crate; callers are expected to fall back to regex extraction.
fn init_parser(language: &str) -> Option<Parser> {
    let lang = language_for(language)?;
    let mut parser = Parser::new();
    parser.set_language(&lang).ok()?;
    Some(parser)
}

// ─── Thread-local Parser cache ──────────────────────────────────────────────
// Each thread gets its own cached `Parser` per language, avoiding repeated
// `Parser::new()` + `set_language()` overhead on every call. A `HashMap` keyed
// by the canonical language name supports all grammar crates without per-language
// statics.

thread_local! {
    static PARSER_CACHE: RefCell<HashMap<String, Parser>> = RefCell::new(HashMap::new());
}

/// Execute a closure with a cached `Parser` for the given language.
///
/// The `Parser` is reused across calls (thread-local cache). This is the
/// preferred entry point for all parse operations. Returns `None` when the
/// language is not supported by the parser backend.
pub fn with_parser<F, R>(language: &str, f: F) -> Option<R>
where
    F: FnOnce(&mut Parser) -> R,
{
    PARSER_CACHE.with(|cache| {
        let mut map = cache.borrow_mut();
        if let Some(parser) = map.get_mut(language) {
            return Some(f(parser));
        }
        let built = init_parser(language)?;
        map.insert(language.to_string(), built);
        let parser = map
            .get_mut(language)
            .expect("invariant: key was just inserted one line above");
        Some(f(parser))
    })
}

/// Create a tree-sitter `Parser` for the given language.
///
/// Returns `None` if the language is not supported.
///
/// **Note**: This creates a new `Parser` each call. Prefer `with_parser()` which
/// reuses a thread-local cached `Parser` instance.
pub fn get_parser(language: &str) -> Option<Parser> {
    init_parser(language)
}

/// AST parsing engine.
///
/// Currently a structural entry point; Phase 1 delegates all analysis
/// to the `analysis` module using regex-based extraction.
/// Phase 2 may integrate tree-sitter here.
pub struct AstEngine;

impl AstEngine {
    /// Create a new `AstEngine` instance.
    pub fn new() -> anyhow::Result<Self> {
        Ok(Self)
    }
}

impl Default for AstEngine {
    fn default() -> Self {
        Self::new().expect("Failed to initialize ast-engine")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detect_rust() {
        assert_eq!(detect_language("main.rs"), Some("rust".to_string()));
        assert_eq!(detect_language("path/to/lib.rs"), Some("rust".to_string()));
    }

    #[test]
    fn detect_typescript() {
        assert_eq!(detect_language("app.ts"), Some("typescript".to_string()));
        assert_eq!(
            detect_language("component.tsx"),
            Some("typescript".to_string())
        );
    }

    #[test]
    fn detect_javascript() {
        assert_eq!(detect_language("index.js"), Some("javascript".to_string()));
        assert_eq!(
            detect_language("module.mjs"),
            Some("javascript".to_string())
        );
    }

    #[test]
    fn detect_python() {
        assert_eq!(detect_language("main.py"), Some("python".to_string()));
        assert_eq!(detect_language("stub.pyi"), Some("python".to_string()));
    }

    #[test]
    fn detect_unknown() {
        assert_eq!(detect_language("data.xyz"), None);
        assert_eq!(detect_language("Makefile"), None);
    }

    #[test]
    fn detect_case_insensitive() {
        assert_eq!(detect_language("Main.RS"), Some("rust".to_string()));
        assert_eq!(detect_language("App.TS"), Some("typescript".to_string()));
    }

    #[test]
    fn ast_engine_new() {
        let _engine = AstEngine::new().unwrap();
    }

    #[test]
    fn ast_engine_default() {
        let _engine = AstEngine::default();
    }

    #[test]
    fn with_parser_reuses_cached_instance() {
        // Calling with_parser twice should succeed and reuse the cached parser.
        let result1 = with_parser("rust", |parser| {
            let tree = parser.parse("fn main() {}", None);
            tree.is_some()
        });
        let result2 = with_parser("rust", |parser| {
            let tree = parser.parse("fn foo() {}", None);
            tree.is_some()
        });
        assert!(result1.unwrap());
        assert!(result2.unwrap());
    }

    #[test]
    fn with_parser_unsupported_language() {
        let result = with_parser("brainfuck", |_parser| 42);
        assert!(result.is_none());
    }

    #[test]
    fn with_parser_supports_multiple_languages() {
        // Smoke test: every enabled language should build a Parser.
        for lang in crate::enabled_languages() {
            let parsed = with_parser(lang, |parser| {
                parser.parse("// placeholder", None).is_some()
            });
            assert!(
                parsed.unwrap_or(false),
                "language `{lang}` failed to build a parser"
            );
        }
    }

    #[test]
    fn sql_parser_abi_compatible_with_024() {
        // tree-sitter 0.24.5 runtime only loads ABI 13/14. The selected SQL
        // grammar (`tree-sitter-sequel`) must report 13/14; ABI 15 (generated
        // by the 0.25 CLI) would be rejected by `set_language` at runtime.
        let lang: tree_sitter::Language = tree_sitter_sequel::LANGUAGE.into();
        let v = lang.version();
        assert!(
            (13..=14).contains(&v),
            "SQL grammar ABI must be 13/14 for tree-sitter 0.24.5, got {v}"
        );
    }

    #[test]
    fn all_enabled_languages_abi_compatible_with_024() {
        // Definitive compatibility check: every enabled language must resolve to a
        // `tree_sitter::Language` whose ABI is 13/14 (the only versions the
        // tree-sitter 0.24.5 runtime loads). A grammar whose published `parser.c`
        // was generated by the 0.25/0.26 CLI reports ABI 15 and is rejected by
        // `set_language` at runtime. We collect ALL incompatible languages in one
        // run rather than panicking on the first, so the report is complete.
        let mut bad = Vec::new();
        for lang in crate::enabled_languages() {
            let language = language_for(lang)
                .unwrap_or_else(|| panic!("enabled language `{lang}` has no language_for entry"));
            let v = language.version();
            if !(13..=14).contains(&v) {
                bad.push((lang, v));
            }
        }
        assert!(
            bad.is_empty(),
            "languages with unsupported ABI (need 13/14 for tree-sitter 0.24.5): {}",
            bad.iter()
                .map(|(l, v)| format!("`{l}`=ABI {v}"))
                .collect::<Vec<_>>()
                .join(", ")
        );
    }
}
