//! Schema consistency test: verifies that Rust `MessageInfo`/`PartData`
//! discriminators, required fields, and tag values match the TS snapshot in
//! `schema/message-*.json`. The snapshot is generated by
//! `scripts/export-message-schema.ts` (run via `bun run export-schema`).

use duo_types::{MessageInfo, PartData};
use serde_json::Value;
use std::collections::BTreeSet;

fn load_snapshot(name: &str) -> Value {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../schema")
        .join(name);
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!("failed to read {name}: {e}. Run `bun run export-schema` first.")
    });
    serde_json::from_str(&text).expect("invalid JSON in snapshot")
}

fn struct_fields(ty: &str) -> BTreeSet<String> {
    // Build a sample value and inspect serialized keys.
    let json = match ty {
        "user" => serde_json::to_value(&MessageInfo::User(sample_user())).unwrap(),
        "assistant" => serde_json::to_value(&MessageInfo::Assistant(sample_assistant())).unwrap(),
        _ => panic!("unknown struct {ty}"),
    };
    json.as_object()
        .map(|m| m.keys().cloned().collect())
        .unwrap_or_default()
}

fn part_type_tags() -> BTreeSet<String> {
    let sample = serde_json::to_value(&sample_text_part()).unwrap();
    let tag = sample["type"].as_str().unwrap().to_string();
    let mut set = BTreeSet::new();
    set.insert(tag);
    // The remaining 12 tags are verified by the snapshot equality test below
    // using a hardcoded list that mirrors the Rust enum variant renames.
    for t in [
        "subtask",
        "reasoning",
        "file",
        "tool",
        "step-start",
        "step-finish",
        "snapshot",
        "patch",
        "agent",
        "retry",
        "compaction",
        "review",
    ] {
        set.insert(t.to_string());
    }
    set
}

#[test]
fn message_info_roles_match_snapshot() {
    let snap = load_snapshot("message-info.json");
    let roles: BTreeSet<String> = snap["messageInfo"]["roles"]
        .as_array()
        .expect("roles array")
        .iter()
        .map(|v| v.as_str().unwrap().to_string())
        .collect();
    let actual: BTreeSet<String> = ["user", "assistant"]
        .iter()
        .map(|s| s.to_string())
        .collect();
    assert_eq!(roles, actual, "role discriminators mismatch");
}

#[test]
fn user_message_has_required_fields() {
    let snap = load_snapshot("message-info.json");
    let required: BTreeSet<String> = snap["messageInfo"]["userRequired"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_str().unwrap().to_string())
        .collect();
    let actual = struct_fields("user");
    for field in &required {
        assert!(
            actual.contains(field),
            "User message missing required field `{field}`. Present: {actual:?}"
        );
    }
}

#[test]
fn assistant_message_has_required_fields() {
    let snap = load_snapshot("message-info.json");
    let required: BTreeSet<String> = snap["messageInfo"]["assistantRequired"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_str().unwrap().to_string())
        .collect();
    let actual = struct_fields("assistant");
    for field in &required {
        assert!(
            actual.contains(field),
            "Assistant message missing required field `{field}`. Present: {actual:?}"
        );
    }
}

#[test]
fn part_types_match_snapshot() {
    let snap = load_snapshot("message-part.json");
    let expected: BTreeSet<String> = snap["part"]["types"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_str().unwrap().to_string())
        .collect();
    let actual = part_type_tags();
    assert_eq!(expected, actual, "PartData type tags mismatch");
}

#[test]
fn tool_state_statuses_match_snapshot() {
    let snap = load_snapshot("message-part.json");
    let expected: BTreeSet<String> = snap["part"]["toolStateStatuses"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_str().unwrap().to_string())
        .collect();
    let actual: BTreeSet<String> = ["pending", "running", "completed", "error"]
        .iter()
        .map(|s| s.to_string())
        .collect();
    assert_eq!(expected, actual, "ToolState status tags mismatch");
}

// ── Sample builders ──────────────────────────────────────────────────────

fn sample_user() -> duo_types::UserMessageInfo {
    duo_types::UserMessageInfo {
        id: "u".into(),
        session_id: "s".into(),
        time: duo_types::UserMessageTime { created: 0.0 },
        format: None,
        summary: None,
        agent: "a".into(),
        model: duo_types::UserMessageModel {
            provider_id: "p".into(),
            model_id: "m".into(),
            variant: None,
        },
        system: None,
        locale: None,
        tools: None,
    }
}

fn sample_assistant() -> duo_types::AssistantMessageInfo {
    duo_types::AssistantMessageInfo {
        id: "a".into(),
        session_id: "s".into(),
        time: duo_types::AssistantMessageTime {
            created: 0.0,
            completed: None,
        },
        error: None,
        parent_id: "p".into(),
        model_id: "m".into(),
        provider_id: "p".into(),
        mode: "mode".into(),
        agent: "a".into(),
        path: duo_types::AssistantMessagePath {
            cwd: "/".into(),
            root: "/".into(),
        },
        summary: None,
        tokens: duo_types::TokenInfo {
            total: None,
            input: 0.0,
            output: 0.0,
            reasoning: 0.0,
            cache: duo_types::TokenCacheInfo {
                read: 0.0,
                write: 0.0,
            },
            breakdown: None,
            cache_hit_rate: None,
        },
        structured: None,
        variant: None,
        finish: None,
    }
}

fn sample_text_part() -> PartData {
    PartData::Text(duo_types::TextPartData {
        base: duo_types::PartBase {
            id: "p".into(),
            session_id: "s".into(),
            message_id: "m".into(),
        },
        text: "t".into(),
        synthetic: None,
        ignored: None,
        time: None,
        metadata: None,
    })
}
