//! Sync LLM configuration to the duoduo sidecar via its HTTP API.
//!
//! When `POST /agent/config` or IM bridge `set_llm_config` is called,
//! this module forwards the configuration to duoduo so that both
//! `auth.json` and `duoduo-ai.json` are kept in sync.

use base64::Engine;
use duo_types::LlmConfig;
use reqwest::Client;
use serde_json::json;
use std::sync::{Mutex, OnceLock};

/// duoduo sidecar credentials, injected by Tauri after the sidecar starts.
///
/// Stored in a `Mutex<Option<..>>` rather than `OnceLock` so it remains
/// writable (e.g. for tests that re-inject a local mock server). In production
/// it is set exactly once from the internal API; the `Err` branch of
/// `set_duoduo_credentials` preserves the previous "set-once" semantics.
static DUODUO_CREDENTIALS: Mutex<Option<DuoduoCredentials>> = Mutex::new(None);

#[derive(Clone)]
pub struct DuoduoCredentials {
    pub url: String,      // e.g. "http://127.0.0.1:4321"
    pub username: String, // "duoduo"
    pub password: String, // uuid generated by Tauri
}

/// Store duoduo credentials (called once from the internal API).
pub fn set_duoduo_credentials(creds: DuoduoCredentials) -> Result<(), DuoduoCredentials> {
    let mut guard = duo_utils::sync::lock(&DUODUO_CREDENTIALS);
    if guard.is_some() {
        return Err(creds);
    }
    *guard = Some(creds);
    Ok(())
}

/// Check if duoduo credentials are available.
pub fn has_duoduo_credentials() -> bool {
    duo_utils::sync::lock(&DUODUO_CREDENTIALS).is_some()
}

/// Return a clone of injected duoduo credentials.
pub fn get_duoduo_credentials() -> Option<DuoduoCredentials> {
    duo_utils::sync::lock(&DUODUO_CREDENTIALS).clone()
}

/// Overwrite any existing credentials. Intended for tests only.
#[cfg(test)]
pub fn reset_duoduo_credentials_for_test(creds: DuoduoCredentials) {
    *duo_utils::sync::lock(&DUODUO_CREDENTIALS) = Some(creds);
}

/// Shared HTTP client for LOOPBACK calls to the duoduo sidecar
/// (lazy-initialized, connection pooling).
///
/// `.no_proxy()` is deliberate: the sidecar is always on 127.0.0.1 — routing
/// it through a corporate proxy would break every call in proxied
/// environments (P1-35 semantics: proxies are for EXTERNAL traffic only).
static HTTP_CLIENT: OnceLock<Client> = OnceLock::new();

pub(crate) fn http_client() -> &'static Client {
    HTTP_CLIENT.get_or_init(|| {
        Client::builder()
            .timeout(std::time::Duration::from_secs(10))
            .connect_timeout(std::time::Duration::from_secs(5))
            .no_proxy()
            .build()
            .expect("invariant: reqwest client built from static config (timeouts, no_proxy) cannot fail")
    })
}

/// Shared HTTP client for EXTERNAL hosts (gear registry downloads, …).
///
/// Same strictness as every other outbound path in this codebase: a connect
/// timeout so a black-holed host fails fast, and an overall timeout so a slow
/// body cannot hang the request forever (P1-32). Unlike the loopback client
/// it does NOT call `.no_proxy()` — external downloads must honor the process
/// proxy environment so corporate-proxy setups keep working (P1-35).
pub(crate) fn external_http_client() -> &'static Client {
    static EXTERNAL_HTTP_CLIENT: OnceLock<Client> = OnceLock::new();
    EXTERNAL_HTTP_CLIENT.get_or_init(|| {
        Client::builder()
            .timeout(std::time::Duration::from_secs(60))
            .connect_timeout(std::time::Duration::from_secs(10))
            .build()
            .unwrap_or_else(|e| {
                tracing::error!(
                    error = %e,
                    "failed to build external HTTP client; falling back to default"
                );
                Client::new()
            })
    })
}

/// Provider ID → npm package mapping.
///
/// duoduo needs to know which SDK to use for each provider.
/// For providers not in this map, fall back to `@ai-sdk/openai-compatible`
/// (which works for any OpenAI-compatible API given a baseURL).
const PROVIDER_NPM_MAP: &[(&str, &str)] = &[
    ("anthropic", "@ai-sdk/anthropic"),
    ("google", "@ai-sdk/google"),
    ("google-vertex", "@ai-sdk/google-vertex"),
    ("azure", "@ai-sdk/azure"),
    ("amazon-bedrock", "@ai-sdk/amazon-bedrock"),
    ("openai", "@ai-sdk/openai"),
];

fn resolve_npm_package(provider_id: &str) -> &'static str {
    PROVIDER_NPM_MAP
        .iter()
        .find(|(id, _)| *id == provider_id)
        .map(|(_, npm)| *npm)
        .unwrap_or("@ai-sdk/openai-compatible")
}

/// Provider ID → human-readable name mapping.
/// Falls back to the provider_id itself if not found.
fn resolve_provider_name(provider_id: &str) -> String {
    // Simple title-case for unknown providers; known ones get proper names.
    match provider_id {
        "xunfei" => "讯飞星火".to_string(),
        "deepseek" => "DeepSeek".to_string(),
        "zhipuai" => "智谱AI".to_string(),
        "alibaba-cn" => "通义千问".to_string(),
        "moonshot" => "Moonshot AI".to_string(),
        "siliconflow" => "SiliconFlow".to_string(),
        "ollama" => "Ollama".to_string(),
        other => {
            // Title-case the ID as a fallback
            let mut s = other.to_string();
            if let Some(c) = s.chars().take(1).next() {
                s = c.to_uppercase().to_string() + &s[c.len_utf8()..];
            }
            s
        }
    }
}

/// Sync LLM config to duoduo. Fire-and-forget: spawned as a background task.
///
/// This function is designed to be called via `tokio::spawn(sync_to_duoduo(config))`
/// so it does not block the caller.
pub async fn sync_to_duoduo(config: LlmConfig) {
    let creds = match duo_utils::sync::lock(&DUODUO_CREDENTIALS).clone() {
        Some(c) => c,
        None => {
            tracing::debug!("duoduo credentials not available, skipping sync");
            return;
        }
    };

    let client = http_client();
    let base = creds.url.trim_end_matches('/');
    let auth_header = format!(
        "Basic {}",
        base64::engine::general_purpose::STANDARD
            .encode(format!("{}:{}", creds.username, creds.password))
    );

    // 1. Sync auth (API key) → PUT /auth/{providerID}
    // If LlmConfig.api_key is None, try to load from OS keyring.
    let resolved_api_key = config
        .api_key
        .clone()
        .or_else(|| crate::secure_store::load_api_key(&config.provider));

    if let Some(ref api_key) = resolved_api_key
        && !api_key.is_empty() {
            let url = format!("{}/auth/{}", base, config.provider);
            let body = json!({
                "type": "api",
                "key": api_key,
            });

            match client
                .put(&url)
                .header("Authorization", &auth_header)
                .header("Content-Type", "application/json")
                .json(&body)
                .send()
                .await
            {
                Ok(resp) if resp.status().is_success() => {
                    tracing::info!(
                        provider = %config.provider,
                        "Synced auth to duoduo"
                    );
                }
                Ok(resp) => {
                    tracing::warn!(
                        provider = %config.provider,
                        status = %resp.status(),
                        "duoduo auth sync failed"
                    );
                }
                Err(e) => {
                    tracing::warn!(
                        provider = %config.provider,
                        error = %e,
                        "duoduo auth sync request failed"
                    );
                }
            }
        }

    // 2. Sync config (provider + model) → PATCH /global/config
    if let Some(ref base_url) = config.base_url {
        if !base_url.trim().is_empty() {
            let provider_id = &config.provider;
            let npm = resolve_npm_package(provider_id);
            let name = resolve_provider_name(provider_id);
            let model_id = &config.default_model_id;

            let url = format!("{}/global/config", base);

            // Build the config body.
            // Note: for non-openai-compatible providers, baseURL in options
            // may not be needed (the SDK knows the endpoint), but including
            // it is harmless and ensures openai-compatible providers work.
            let mut provider_json = json!({
                "name": name,
                "npm": npm,
                "models": {
                    model_id: {
                        "name": model_id,
                    }
                }
            });

            // Only set options.apiKey and options.baseURL for openai-compatible
            // providers that need them. Official SDK providers (anthropic, google, etc.)
            // resolve keys from auth.json automatically.
            if npm == "@ai-sdk/openai-compatible" {
                provider_json["options"] = json!({
                    "baseURL": base_url,
                });
                if let Some(ref key) = resolved_api_key
                    && !key.is_empty() {
                        provider_json["options"]["apiKey"] = json!(key);
                    }
            }

            let body = json!({
                "provider": {
                    provider_id: provider_json,
                }
            });

            match client
                .patch(&url) // ← PATCH, NOT PUT
                .header("Authorization", &auth_header)
                .header("Content-Type", "application/json")
                .json(&body)
                .send()
                .await
            {
                Ok(resp) if resp.status().is_success() => {
                    tracing::info!(
                        provider = %provider_id,
                        model = %model_id,
                        "Synced config to duoduo"
                    );
                }
                Ok(resp) => {
                    tracing::warn!(
                        provider = %provider_id,
                        status = %resp.status(),
                        "duoduo config sync failed"
                    );
                }
                Err(e) => {
                    tracing::warn!(
                        provider = %provider_id,
                        error = %e,
                        "duoduo config sync request failed"
                    );
                }
            }
        }
    } else {
        tracing::debug!(
            provider = %config.provider,
            "No base_url, skipping duoduo config sync"
        );
    }
}
