//! Environment variable key constants for DuoDuo configuration.
//!
//! Centralizes all `DUO_*` and related environment variable names so they are
//! defined in one place. Crates should use these constants instead of inline
//! string literals to avoid typos and enable greppability.

/// Smart-layer service environment variables.
pub mod smart_layer {
    /// Port for the smart-layer HTTP server. `0` = random port.
    pub const PORT: &str = "DUO_SMART_LAYER_PORT";
    /// Bind hostname for the smart-layer HTTP server.
    pub const HOSTNAME: &str = "DUO_SMART_LAYER_HOSTNAME";
    /// Password for smart-layer Basic Auth (generated by Tauri at startup).
    pub const PASSWORD: &str = "DUO_SMART_LAYER_PASSWORD";
    /// Base URL of the smart-layer (injected into sidecar processes).
    pub const URL: &str = "DUO_SMART_LAYER_URL";
    /// Comma-separated list of allowed CORS origins (overrides defaults).
    pub const CORS_ALLOWED_ORIGINS: &str = "CORS_ALLOWED_ORIGINS";
    /// Stdout marker emitted when the smart-layer process is ready to accept connections.
    /// Format: `DUO_SMART_LAYER_READY|port={port}`.
    pub const READY_MARKER: &str = "DUO_SMART_LAYER_READY|port=";
}

/// IM (Instant Messaging) bridge environment variables.
pub mod im {
    /// Global IM on/off switch (`true`/`false`).
    pub const ENABLED: &str = "DUO_IM_ENABLED";
    /// Fallback project path for development/debugging.
    pub const DEFAULT_PROJECT_PATH: &str = "DUO_IM_DEFAULT_PROJECT_PATH";
    /// Notify configured chats when IDE tasks complete.
    pub const NOTIFY_ON_COMPLETE: &str = "DUO_IM_NOTIFY_ON_COMPLETE";
    /// Feishu App ID.
    pub const FEISHU_APP_ID: &str = "DUO_IM_FEISHU_APP_ID";
    /// Feishu App Secret.
    pub const FEISHU_APP_SECRET: &str = "DUO_IM_FEISHU_APP_SECRET";
    /// Feishu domain: `"feishu"` or `"lark"`.
    pub const FEISHU_DOMAIN: &str = "DUO_IM_FEISHU_DOMAIN";
}

/// Core DuoDuo service environment variables (used by config-manager).
pub mod core {
    /// Port for the DuoDuo backend server.
    pub const PORT: &str = "DUO_PORT";
    /// Bind hostname for the DuoDuo backend server.
    pub const HOSTNAME: &str = "DUO_HOSTNAME";
    /// Log level (`"info"`, `"debug"`, etc.).
    pub const LOG_LEVEL: &str = "DUO_LOG_LEVEL";
    /// Auth token for API access.
    pub const AUTH_TOKEN: &str = "DUO_AUTH_TOKEN";
    /// Path to the SQLite database file.
    pub const DB_PATH: &str = "DUO_DB_PATH";
}

/// Feature flag environment variables (`DUO_FF_*`).
pub mod feature_flags {
    /// Build a stable-prefix send-view each round.
    pub const STABLE_PREFIX: &str = "DUO_FF_STABLE_PREFIX";
    /// Recursively sort JSON-object keys in `ToolDefinition.parameters`.
    pub const CANONICALIZE_TOOLS: &str = "DUO_FF_CANONICALIZE_TOOLS";
    /// De-duplicate identical tool calls within a single round.
    pub const TOOL_DEDUP: &str = "DUO_FF_TOOL_DEDUP";
    /// Enable mid-loop quality checks (SelfCheck after edit_file/submit_code).
    pub const LOOP_QUALITY_MID_CHECK: &str = "DUO_FF_LOOP_QUALITY_MID_CHECK";
}

/// Standard HTTP proxy environment variable names.
pub mod proxy {
    /// `NO_PROXY` — list of hosts that bypass the proxy (uppercase convention).
    pub const NO_PROXY: &str = "NO_PROXY";
    /// `no_proxy` — lowercase variant recognized by some HTTP libraries.
    pub const NO_PROXY_LOWER: &str = "no_proxy";
}
